name = "tor-taxi-rs-worker"
main = "build/index.js"
compatibility_date = "2026-09-08"

[build]
command = "cargo leptos build --release && cargo install -q \"worker-build@^0.8\" && LEPTOS_OUTPUT_NAME=tor-taxi-rs-worker worker-build --release --features ssr"

[assets]
directory = "../../target/site"

[[d1_databases]]
binding = "prod_links"
database_name = "prod-links"
database_id = "e068c0b1-827b-408d-9e94-220ba77d6c33"
