[dread]
url = "https://dreadytofatroptsdj6io7l3xptbet6onoyno2yv7jicoxknyazubrad.onion/"
description = "it's Dread"
category = "Forum"

[dnm_bible]
url = "http://biblemeowimkh3utujmhm6oh2oeb3ubjw2lpgeq3lahrfr2l6ev6zgyd.onion/"
description = "Darknet market bible"
category = "Info"


[opsec_bible]
url = "http://jqibjqqagao3peozxfs53tr6aecoyvctumfsc2xqniu4xgcrksal2iqd.onion/"
description = "OPSEC bible"
category = "Info"

